### ISSUE TITLE
Use of ed25519/signature crate types

### ISSUE THREAD

**Issue by jhbruhn** [nickray/salty#23]
ed25519-dalek and other implementations make use of the generic types defined in the [signature](https://docs.rs/signature/1.4.0/signature/trait.Signature.html) crate to be able to do a generic implementation over multiple potential signing algorithms.
Is there a specific reason this crate does not implement these traits? Or am I missing something?

I understand that the Signature type from [ed25519](https://docs.rs/ed25519/1.3.0/ed25519/index.html) is not used due to the optimized in-memory storage done in this library, but maybe providing From<> impls for those types could make a nice API?

I'm considering doing a PR for this but want to hear your opinion first.

**Comment by nickray** [comment]
Yes that would be a nice addition! Also the other lightweight traits 😉
