### ISSUE TITLE
Cant build this on linux

### ISSUE THREAD

**Issue by daveHitchman** [nickray/salty#30]
I have added everything I think should be needed (some documents would help) 
I get a shed of errors starting with:
dave@dave-TUXEDO-Aura-15-Gen1:~/git/solokeys/solo1/crypto/salty/c-api$ make build
cargo build --release --target thumbv7em-none-eabihf
   Compiling subtle v2.4.1
   Compiling panic-halt v0.2.0
   Compiling salty v0.1.0-alpha.1 (/home/dave/git/solokeys/solo1/crypto/salty)
error[E0463]: can't find crate for `core`
  |
  = note: the `thumbv7em-none-eabihf` target may not be installed
  = help: consider downloading the target with `rustup target add thumbv7em-none-eabihf`

error[E0463]: can't find crate for `compiler_builtins`

error[E0433]: failed to resolve: use of undeclared crate or module `atomic`
  --> /home/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/panic-halt-0.2.0/src/lib.rs:33:9

I am willing to believe this is my fault but some pointers in the readme towards what is needed to be installed where and how for this to work would make life (especially mine) far far easier, then we would all be able to benefit from the hardwork that has obviously been put in. 
I am trying to compile the solokey solo1 project, that at last compiles but apparently it needs the salty library

**Comment by nickray** [comment]
The error message tells you: run `rustup target add thumbv7em-none-eabihf`.
