### ISSUE TITLE
Accept non-canonical encodings of X25519 public keys

### ISSUE THREAD

**Issue by sosthene-nitrokey** [nickray/salty#31]
Currently `agreement::PublicKey` only implements `TryFrom<[u8;32]>` instead of `From`

This prevents using non-canonical curve elements. However, the standardised `x25519` function has a signature of  `x25519(k: [u8; 32], u: [u8; 32]) -> [u8; 32]` which doesn't fail and silently canonicalize the public type.

For example [`x25519-dalek` implements `From`](https://docs.rs/x25519-dalek/latest/x25519_dalek/struct.PublicKey.html#impl-From%3C%5Bu8%3B%2032%5D%3E).

**Comment by sosthene-nitrokey** [comment]
It looks like https://github.com/ycrypto/salty/commit/01404bc260e1b5ef12206996cae515d794caea61 should have instead used `from_unreduced_bytes`?

**Comment by nickray** [comment]
I think this is a weird use case to use `[0xFF; 32]` as public key, but [RFC 7748](https://datatracker.ietf.org/doc/html/rfc7748#section-5) agrees.
